config/routes.rb
AdminHr::Application.routes.draw do
  devise_for :admins

  match 'admin' => 'admin#index'

  resource :admin, only: :show, format: false

  scope "api" do
    resources :employees
  end

  root :to => 'admin#index'

end
#== Route Map
# Generated on 13 Oct 2012 16:21
#
#         admin_session POST   /admins/sign_in(.:format)         devise/sessions#create
# destroy_admin_session DELETE /admins/sign_out(.:format)        devise/sessions#destroy
#        admin_password POST   /admins/password(.:format)        devise/passwords#create
#    new_admin_password GET    /admins/password/new(.:format)    devise/passwords#new
#   edit_admin_password GET    /admins/password/edit(.:format)   devise/passwords#edit
#                       PUT    /admins/password(.:format)        devise/passwords#update
#                 admin        /admin(.:format)                  admin#index
#                       GET    /admin                            admins#show
#             employees GET    /api/employees(.:format)          employees#index
#                       POST   /api/employees(.:format)          employees#create
#          new_employee GET    /api/employees/new(.:format)      employees#new
#         edit_employee GET    /api/employees/:id/edit(.:format) employees#edit
#              employee GET    /api/employees/:id(.:format)      employees#show
#                       PUT    /api/employees/:id(.:format)      employees#update
#                       DELETE /api/employees/:id(.:format)      employees#destroy
#                  root        /                                 admin#index

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :address_line_1, :address_line_2, :country, :date_of_birth, :first_name, :gender, :home_email, :home_phone, :last_name, :marital_status, :middle_name, :mobile_phone, :nickname, :passport_expiration_date, :passport_number, :second_last_name, :shirt_size, :ssn, :state, :status, :visa_expiration_date, :visa_type, :work_email, :zip_code
  #searchable do
    #integer :id, stored: true
    #text(:full_name, stored: true) do
      #[first_name, last_name, work_email, home_email, home_phone].join(' ')
    #end
  #end

  #def filter keywords
    #self.search do
      #fulltext keywords
    #end.results
  #end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_filter :authenticate_admin!

  def index

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  respond_to :json

  def index
    employees = if params[:keywords]
                  #Employee.search { keywords params[:keywords] }.results
                  Employee.where("middle_name ILIKE ? OR first_name ILIKE ? or last_name ILIKE ?",
                                 "%#{params[:keywords]}%", "%#{params[:keywords]}%", "%#{params[:keywords]}%")
                else
                  Employee.all
    end
    respond_with employees
  end

  def create
    respond_with Employee.create(params[:employee])
  end

  def show
    respond_with Employee.find(params[:id])
  end

  def update
    respond_with Employee.update(params[:id], params[:employee])
  end

  def destroy
    respond_with Employee.destroy(params[:id])
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.haml
#container-app

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Dedicated HR Manager
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    %header
      = render 'shared/navbar'
      - unless notice.blank? && alert.blank?
        - unless notice.blank?
          %p.notice= notice
      - unless alert.blank?
        .notification.red
          %p.alert= alert

    %section
      = yield
    %footer

    :javascript
      $(document).ready(function(){
        AdminHr.init()
      });

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %title Dedicated HR Manager
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body.login-page
    %header
    %section#main
      = yield
    %footer

app/views/shared/_navbar.html.haml
.navbar.navbar-inverse{:style => "position: static;"}
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".subnav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand{:href => "#"} Dedicated HR Manager
      .nav-collapse.subnav-collapse.in.collapse
        %ul.nav
          %li.active
            %a{:href => "#"} Dashboard
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Personal Information
              %b.caret
            %ul.dropdown-menu
              %li
                %a{:href => "#crew"} Crew
              %li
                %a{:href => "#"} Job
              %li
                %a{:href => "#"} Project
              %li
                %a{:href => "#"} Emergency Contacts
              %li
                %a{:href => "#"} Dependents
              %li.divider
              %li.nav-header Admin
              %li
                %a{:href => "#"} Benefits
              %li
                %a{:href => "#"} Time Off
          -#%form.navbar-search.pull-left{:action => ""}
            -#%input.search-query.span2{:placeholder => "Search Employee",id: 'searchEmployee', :type => "text"}
        %ul.nav.pull-right
          %li
            = link_to current_admin.email, '#'
          %li.divider-vertical
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Profile
              %b.caret
            %ul.dropdown-menu
              %li
                %a{:href => "#"} About Admin HR
              %li
                %a{:href => "#"} Help
              %li.divider
              %li
                = link_to('Sign out', destroy_admin_session_path, :method => :delete)